### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `CosineAnnealingLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

### ISSUE THREAD

**Issue by dhgras** [snap-research/MobileR2L#2]
When I was training the Teacher, to running `sh benchmarking/benchmark_synthetic_nerf.sh lego`, I encountered the following problem: 

Traceback (most recent call last):
  File "/workspace/MobileR2L/model/teacher/ngp_pl/train.py", line 427, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/strategies/single_device.py", line 74, in setup
    super().setup(trainer)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 153, in setup
    self.setup_optimizers(trainer)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 141, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 194, in _init_optimizers_and_lr_schedulers
    _validate_scheduler_api(lr_scheduler_configs, model)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 351, in _validate_scheduler_api
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `CosineAnnealingLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

My CUDA version is 11.8, so I installed `torch=2.0.0+cu11.8` in ngp_pl, and everything else is the same as README.

So how should I solve this problem?

**Comment by dhgras** [comment]
I can roughly confirm that there is a compatibility issue between versions pytorch, cuda, and pytorch-lighting.
![image](https://github.com/snap-research/MobileR2L/assets/42953352/dea55311-d413-4941-8a59-b17bf993d77d)

So how should I configure the ngp_pl environment on my device, which is cuda=11.8?

**Comment by galalalala** [comment]
Hi, `ngp_pl` environment is bit tricky to setup as its dependecies such as `torch-scatter` and `apex` needs a specific cuda version. That's why we recommend to use a sepertate `conda` environment with cuda=11.6 for `ngp_pl`. I remember `apex` will throw some building errors if using `torch=2.0 + cuda=11.7` back then. That being said, it would be easier to use the recommended configurations to setup `ngp_pl` instead of modifying the codebase.
